### ISSUE TITLE
Zamodelowanie danych wejściowych

### ISSUE THREAD

**Issue by lemime** [kjuszczak96/buildingInfo#4]
Struktura   danych
- Budynek może składać się z poziomów a te z pomieszczeń
- Każda lokalizacja jest charakteryzowana przez:    
    id – unikalny   identyfikator
   name – opcjonalna nazwa   lokalizacji     
- Pomieszczenie dodatkowo jest charakteryzowane przez:      
 area = powierzchnia w m^2 
 cube = kubatura pomieszczenia w   m^3
 heating = poziom zużycia energii   ogrzewania (float)  
 light – łączna moc   oświetlenia

**Comment by fiffikrul** [comment]
Czyli pomieszczenie od poziomu/budynku rozróżniamy tym, że ma te wartości? Wie ktoś jak odróżnić poziom od budynku?
